#############################################################################
# Makefile for building: NarutoCardGame.app/Contents/MacOS/NarutoCardGame
# Generated by qmake (3.0) (Qt 5.0.1) on: Wed Apr 10 15:23:03 2013
# Project:  NarutoCardGame.pro
# Template: app
# Command: /Applications/Qt5.0.1/5.0.1/clang_64/bin/qmake -spec macx-clang CONFIG+=debug CONFIG+=x86_64 -o Makefile NarutoCardGame.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = clang
CXX           = clang++
DEFINES       = -DQT_XML_LIB -DQT_NETWORK_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -mmacosx-version-min=10.6 -g -gdwarf-2 -Wall -W -fPIE $(DEFINES)
CXXFLAGS      = -pipe -mmacosx-version-min=10.6 -g -gdwarf-2 -Wall -W -fPIE $(DEFINES)
INCPATH       = -I/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/macx-clang -I. -I/Applications/Qt5.0.1/5.0.1/clang_64/include -I/Applications/Qt5.0.1/5.0.1/clang_64/include/QtXml -I/Applications/Qt5.0.1/5.0.1/clang_64/lib/QtXml.framework/Versions/5/Headers -I/Applications/Qt5.0.1/5.0.1/clang_64/include/QtNetwork -I/Applications/Qt5.0.1/5.0.1/clang_64/lib/QtNetwork.framework/Versions/5/Headers -I/Applications/Qt5.0.1/5.0.1/clang_64/include/QtGui -I/Applications/Qt5.0.1/5.0.1/clang_64/lib/QtGui.framework/Versions/5/Headers -I/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore -I/Applications/Qt5.0.1/5.0.1/clang_64/lib/QtCore.framework/Versions/5/Headers -I. -I/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers -I/System/Library/Frameworks/AGL.framework/Headers
LINK          = clang++
LFLAGS        = -headerpad_max_install_names -mmacosx-version-min=10.6
LIBS          = $(SUBLIBS) -F/Applications/Qt5.0.1/5.0.1/clang_64/lib -framework QtXml -F/Applications/Qt5.0.1/5.0.1/clang_64/qtbase/lib -framework QtCore -framework QtNetwork -framework QtGui -framework OpenGL -framework AGL 
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /Applications/Qt5.0.1/5.0.1/clang_64/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		card.cpp \
		player.cpp \
		ninja.cpp \
		technique.cpp \
		tactique.cpp \
		client.cpp moc_mainwindow.cpp
OBJECTS       = main.o \
		mainwindow.o \
		card.o \
		player.o \
		ninja.o \
		technique.o \
		tactique.o \
		client.o \
		moc_mainwindow.o
DIST          = /Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/features/spec_pre.prf \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/qdevice.pri \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/features/device_config.prf \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/common/shell-unix.conf \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/common/unix.conf \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/common/mac.conf \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/common/gcc-base.conf \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/common/gcc-base-macx.conf \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/common/clang.conf \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/common/clang-mac.conf \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/common/mac-minimum-version.conf \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/qconfig.pri \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_bootstrap.pri \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_clucene.pri \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_designercomponents.pri \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_platformsupport.pri \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_qmldevtools.pri \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_quickparticles.pri \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_script.pri \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_v8.pri \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/features/qt_functions.prf \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/features/qt_config.prf \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/macx-clang/qmake.conf \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/features/spec_post.prf \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/features/exclusive_builds.prf \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/features/default_pre.prf \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/features/unix/default_pre.prf \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/features/mac/default_pre.prf \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/features/debug.prf \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/features/default_post.prf \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/features/mac/default_post.prf \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/features/mac/objective_c.prf \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/features/shared.prf \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/features/warn_on.prf \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/features/qt.prf \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/features/resources.prf \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/features/moc.prf \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/features/unix/opengl.prf \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/features/unix/thread.prf \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/features/mac/rez.prf \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/features/mac/sdk.prf \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/features/testcase_targets.prf \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/features/exceptions.prf \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/features/yacc.prf \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/features/lex.prf \
		NarutoCardGame.pro \
		NarutoCardGame.pro
QMAKE_TARGET  = NarutoCardGame
DESTDIR       = 
TARGET        = NarutoCardGame.app/Contents/MacOS/NarutoCardGame

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-mmacosx-version-min=10.6 \
		-g \
		-gdwarf-2 \
		-Wall \
		-W



first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile NarutoCardGame.app/Contents/PkgInfo NarutoCardGame.app/Contents/Resources/empty.lproj NarutoCardGame.app/Contents/Info.plist $(TARGET)

$(TARGET):  $(OBJECTS)  
	@test -d NarutoCardGame.app/Contents/MacOS/ || $(MKDIR) NarutoCardGame.app/Contents/MacOS/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: NarutoCardGame.pro /Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/macx-clang/qmake.conf /Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/features/spec_pre.prf \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/qdevice.pri \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/features/device_config.prf \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/common/shell-unix.conf \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/common/unix.conf \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/common/mac.conf \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/common/gcc-base.conf \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/common/gcc-base-macx.conf \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/common/clang.conf \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/common/clang-mac.conf \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/common/mac-minimum-version.conf \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/qconfig.pri \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_bootstrap.pri \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_clucene.pri \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_designercomponents.pri \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_platformsupport.pri \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_qmldevtools.pri \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_quickparticles.pri \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_script.pri \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_v8.pri \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/features/qt_functions.prf \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/features/qt_config.prf \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/macx-clang/qmake.conf \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/features/spec_post.prf \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/features/exclusive_builds.prf \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/features/default_pre.prf \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/features/unix/default_pre.prf \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/features/mac/default_pre.prf \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/features/debug.prf \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/features/default_post.prf \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/features/mac/default_post.prf \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/features/mac/objective_c.prf \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/features/shared.prf \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/features/warn_on.prf \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/features/qt.prf \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/features/resources.prf \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/features/moc.prf \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/features/unix/opengl.prf \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/features/unix/thread.prf \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/features/mac/rez.prf \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/features/mac/sdk.prf \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/features/testcase_targets.prf \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/features/exceptions.prf \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/features/yacc.prf \
		/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/features/lex.prf \
		NarutoCardGame.pro \
		/Applications/Qt5.0.1/5.0.1/clang_64/lib/QtXml.framework/QtXml.prl \
		/Applications/Qt5.0.1/5.0.1/clang_64/lib/QtCore.framework/QtCore.prl \
		/Applications/Qt5.0.1/5.0.1/clang_64/lib/QtNetwork.framework/QtNetwork.prl \
		/Applications/Qt5.0.1/5.0.1/clang_64/lib/QtGui.framework/QtGui.prl
	$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 -o Makefile NarutoCardGame.pro
/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/features/spec_pre.prf:
/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/qdevice.pri:
/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/features/device_config.prf:
/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/common/shell-unix.conf:
/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/common/unix.conf:
/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/common/mac.conf:
/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/common/gcc-base.conf:
/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/common/gcc-base-macx.conf:
/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/common/clang.conf:
/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/common/clang-mac.conf:
/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/common/mac-minimum-version.conf:
/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/qconfig.pri:
/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_bootstrap.pri:
/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_clucene.pri:
/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_core.pri:
/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_declarative.pri:
/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_designer.pri:
/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_designercomponents.pri:
/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_gui.pri:
/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_help.pri:
/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_network.pri:
/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_opengl.pri:
/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_platformsupport.pri:
/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_qml.pri:
/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_qmldevtools.pri:
/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri:
/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_quick.pri:
/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_quickparticles.pri:
/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_script.pri:
/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_sql.pri:
/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_svg.pri:
/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_testlib.pri:
/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_uitools.pri:
/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_v8.pri:
/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_webkit.pri:
/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_widgets.pri:
/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_xml.pri:
/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/features/qt_functions.prf:
/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/features/qt_config.prf:
/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/macx-clang/qmake.conf:
/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/features/spec_post.prf:
/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/features/exclusive_builds.prf:
/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/features/default_pre.prf:
/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/features/unix/default_pre.prf:
/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/features/mac/default_pre.prf:
/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/features/debug.prf:
/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/features/default_post.prf:
/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/features/mac/default_post.prf:
/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/features/mac/objective_c.prf:
/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/features/shared.prf:
/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/features/warn_on.prf:
/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/features/qt.prf:
/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/features/resources.prf:
/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/features/moc.prf:
/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/features/unix/opengl.prf:
/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/features/unix/thread.prf:
/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/features/mac/rez.prf:
/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/features/mac/sdk.prf:
/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/features/testcase_targets.prf:
/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/features/exceptions.prf:
/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/features/yacc.prf:
/Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/features/lex.prf:
NarutoCardGame.pro:
/Applications/Qt5.0.1/5.0.1/clang_64/lib/QtXml.framework/QtXml.prl:
/Applications/Qt5.0.1/5.0.1/clang_64/lib/QtCore.framework/QtCore.prl:
/Applications/Qt5.0.1/5.0.1/clang_64/lib/QtNetwork.framework/QtNetwork.prl:
/Applications/Qt5.0.1/5.0.1/clang_64/lib/QtGui.framework/QtGui.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 -o Makefile NarutoCardGame.pro

qmake_all: FORCE

NarutoCardGame.app/Contents/PkgInfo: 
	@test -d NarutoCardGame.app/Contents || $(MKDIR) NarutoCardGame.app/Contents 
	@$(DEL_FILE) NarutoCardGame.app/Contents/PkgInfo
	@echo "APPL????" >NarutoCardGame.app/Contents/PkgInfo
NarutoCardGame.app/Contents/Resources/empty.lproj: 
	@test -d NarutoCardGame.app/Contents/Resources || $(MKDIR) NarutoCardGame.app/Contents/Resources 
	@touch NarutoCardGame.app/Contents/Resources/empty.lproj
	
NarutoCardGame.app/Contents/Info.plist: 
	@test -d NarutoCardGame.app/Contents || $(MKDIR) NarutoCardGame.app/Contents 
	@$(DEL_FILE) NarutoCardGame.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,NarutoCardGame,g" -e "s,@TYPEINFO@,????,g" /Applications/Qt5.0.1/5.0.1/clang_64/mkspecs/macx-clang/Info.plist.app >NarutoCardGame.app/Contents/Info.plist
dist: 
	@test -d .tmp/NarutoCardGame1.0.0 || $(MKDIR) .tmp/NarutoCardGame1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/NarutoCardGame1.0.0/ && $(COPY_FILE) --parents mainwindow.h card.h player.h ninja.h technique.h tactique.h client.h .tmp/NarutoCardGame1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp card.cpp player.cpp ninja.cpp technique.cpp tactique.cpp client.cpp .tmp/NarutoCardGame1.0.0/ && (cd `dirname .tmp/NarutoCardGame1.0.0` && $(TAR) NarutoCardGame1.0.0.tar NarutoCardGame1.0.0 && $(COMPRESS) NarutoCardGame1.0.0.tar) && $(MOVE) `dirname .tmp/NarutoCardGame1.0.0`/NarutoCardGame1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/NarutoCardGame1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r NarutoCardGame.app
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: mainwindow.h
	/Applications/Qt5.0.1/5.0.1/clang_64/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__=4 mainwindow.h -o moc_mainwindow.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cpp mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		ui_mainwindow.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/QVariant \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qvariant.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qglobal.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qconfig.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qfeatures.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qsystemdetection.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qcompilerdetection.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qprocessordetection.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qlogging.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qflags.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qtypeinfo.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qtypetraits.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qsysinfo.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qbasicatomic.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_bootstrap.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qgenericatomic.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_msvc.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_integrity.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qoldbasicatomic.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_vxworks.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_power.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_alpha.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_armv7.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_armv6.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_armv5.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_bfin.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_ia64.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_mips.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_s390.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_sh4a.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_sparc.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_x86.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_cxx11.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_gcc.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_unix.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qbytearray.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qrefcount.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qnamespace.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qarraydata.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qstring.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qchar.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qstringbuilder.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qlist.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qalgorithms.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qiterator.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qmetatype.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qvarlengtharray.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qcontainerfwd.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qisenum.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qobjectdefs.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qobjectdefs_impl.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qmap.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qpair.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qdebug.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qhash.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qtextstream.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qiodevice.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qobject.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qcoreevent.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qscopedpointer.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qobject_impl.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qlocale.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qshareddata.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qvector.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qpoint.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qset.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qcontiguouscache.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtWidgets/QAction \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtWidgets/qaction.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtGui/qkeysequence.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtWidgets/qwidget.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtGui/qwindowdefs.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtGui/qwindowdefs_win.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qmargins.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtGui/qpaintdevice.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qrect.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qsize.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtGui/qpalette.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtGui/qcolor.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtGui/qrgb.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qstringlist.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qdatastream.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qregexp.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qstringmatcher.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtGui/qbrush.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtGui/qmatrix.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtGui/qpolygon.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtGui/qregion.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qline.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtGui/qtransform.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtGui/qpainterpath.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtGui/qimage.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtGui/qpixmap.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qsharedpointer.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qsharedpointer_impl.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtGui/qfont.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtGui/qfontmetrics.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtGui/qfontinfo.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtWidgets/qsizepolicy.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtGui/qcursor.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtGui/qevent.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qurl.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qurlquery.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qfile.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qfiledevice.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtGui/qvector2d.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtGui/qtouchdevice.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtGui/qicon.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtWidgets/qactiongroup.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtWidgets/QApplication \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtWidgets/qapplication.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qcoreapplication.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qeventloop.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtWidgets/qdesktopwidget.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtGui/qguiapplication.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtGui/qinputmethod.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtWidgets/QButtonGroup \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtWidgets/qbuttongroup.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtWidgets/QHeaderView \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtWidgets/qheaderview.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtWidgets/qabstractitemview.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtWidgets/qabstractscrollarea.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtWidgets/qframe.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qabstractitemmodel.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qitemselectionmodel.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtWidgets/qabstractitemdelegate.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtWidgets/qstyleoption.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtWidgets/qabstractspinbox.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtGui/qvalidator.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtWidgets/qslider.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtWidgets/qabstractslider.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtWidgets/qstyle.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtWidgets/qtabbar.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtWidgets/qtabwidget.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtWidgets/qrubberband.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtWidgets/QMainWindow \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtWidgets/qmainwindow.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtWidgets/QMenuBar \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtWidgets/qmenubar.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtWidgets/qmenu.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtWidgets/QStatusBar \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtWidgets/qstatusbar.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtWidgets/QToolBar \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtWidgets/qtoolbar.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtWidgets/QWidget
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

card.o: card.cpp card.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/QObject \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qobject.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qobjectdefs.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qnamespace.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qglobal.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qconfig.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qfeatures.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qsystemdetection.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qcompilerdetection.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qprocessordetection.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qlogging.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qflags.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qtypeinfo.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qtypetraits.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qsysinfo.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qobjectdefs_impl.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qstring.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qchar.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qbytearray.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qrefcount.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qbasicatomic.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_bootstrap.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qgenericatomic.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_msvc.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_integrity.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qoldbasicatomic.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_vxworks.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_power.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_alpha.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_armv7.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_armv6.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_armv5.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_bfin.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_ia64.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_mips.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_s390.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_sh4a.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_sparc.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_x86.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_cxx11.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_gcc.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_unix.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qarraydata.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qstringbuilder.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qlist.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qalgorithms.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qiterator.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qcoreevent.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qscopedpointer.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qmetatype.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qvarlengtharray.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qcontainerfwd.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qisenum.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qobject_impl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o card.o card.cpp

player.o: player.cpp player.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/QObject \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qobject.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qobjectdefs.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qnamespace.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qglobal.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qconfig.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qfeatures.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qsystemdetection.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qcompilerdetection.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qprocessordetection.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qlogging.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qflags.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qtypeinfo.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qtypetraits.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qsysinfo.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qobjectdefs_impl.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qstring.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qchar.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qbytearray.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qrefcount.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qbasicatomic.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_bootstrap.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qgenericatomic.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_msvc.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_integrity.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qoldbasicatomic.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_vxworks.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_power.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_alpha.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_armv7.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_armv6.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_armv5.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_bfin.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_ia64.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_mips.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_s390.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_sh4a.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_sparc.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_x86.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_cxx11.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_gcc.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_unix.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qarraydata.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qstringbuilder.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qlist.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qalgorithms.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qiterator.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qcoreevent.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qscopedpointer.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qmetatype.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qvarlengtharray.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qcontainerfwd.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qisenum.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qobject_impl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o player.o player.cpp

ninja.o: ninja.cpp ninja.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ninja.o ninja.cpp

technique.o: technique.cpp technique.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/QObject \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qobject.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qobjectdefs.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qnamespace.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qglobal.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qconfig.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qfeatures.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qsystemdetection.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qcompilerdetection.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qprocessordetection.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qlogging.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qflags.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qtypeinfo.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qtypetraits.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qsysinfo.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qobjectdefs_impl.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qstring.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qchar.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qbytearray.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qrefcount.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qbasicatomic.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_bootstrap.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qgenericatomic.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_msvc.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_integrity.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qoldbasicatomic.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_vxworks.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_power.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_alpha.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_armv7.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_armv6.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_armv5.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_bfin.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_ia64.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_mips.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_s390.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_sh4a.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_sparc.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_x86.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_cxx11.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_gcc.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_unix.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qarraydata.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qstringbuilder.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qlist.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qalgorithms.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qiterator.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qcoreevent.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qscopedpointer.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qmetatype.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qvarlengtharray.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qcontainerfwd.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qisenum.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qobject_impl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o technique.o technique.cpp

tactique.o: tactique.cpp tactique.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/QObject \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qobject.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qobjectdefs.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qnamespace.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qglobal.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qconfig.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qfeatures.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qsystemdetection.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qcompilerdetection.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qprocessordetection.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qlogging.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qflags.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qtypeinfo.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qtypetraits.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qsysinfo.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qobjectdefs_impl.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qstring.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qchar.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qbytearray.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qrefcount.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qbasicatomic.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_bootstrap.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qgenericatomic.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_msvc.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_integrity.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qoldbasicatomic.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_vxworks.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_power.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_alpha.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_armv7.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_armv6.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_armv5.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_bfin.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_ia64.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_mips.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_s390.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_sh4a.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_sparc.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_x86.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_cxx11.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_gcc.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_unix.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qarraydata.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qstringbuilder.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qlist.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qalgorithms.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qiterator.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qcoreevent.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qscopedpointer.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qmetatype.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qvarlengtharray.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qcontainerfwd.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qisenum.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qobject_impl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tactique.o tactique.cpp

client.o: client.cpp client.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/QObject \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qobject.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qobjectdefs.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qnamespace.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qglobal.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qconfig.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qfeatures.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qsystemdetection.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qcompilerdetection.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qprocessordetection.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qlogging.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qflags.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qtypeinfo.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qtypetraits.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qsysinfo.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qobjectdefs_impl.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qstring.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qchar.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qbytearray.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qrefcount.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qbasicatomic.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_bootstrap.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qgenericatomic.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_msvc.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_integrity.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qoldbasicatomic.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_vxworks.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_power.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_alpha.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_armv7.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_armv6.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_armv5.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_bfin.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_ia64.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_mips.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_s390.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_sh4a.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_sparc.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_x86.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_cxx11.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_gcc.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qatomic_unix.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qarraydata.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qstringbuilder.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qlist.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qalgorithms.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qiterator.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qcoreevent.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qscopedpointer.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qmetatype.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qvarlengtharray.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qcontainerfwd.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qisenum.h \
		/Applications/Qt5.0.1/5.0.1/clang_64/include/QtCore/qobject_impl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o client.o client.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

